config/routes.rb
Rails.application.routes.draw do
  root 'billboards#index'

  resources :billboards do
    resources :artists
  end

  

 resources :artists do
   resources :songs
   end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :billboard, optional: true
  has_many :songs, dependent: :destroy
  
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :artists, dependent: :destroy
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_billboard
  before_action :set_artist, only: [:show, :edit, :update, :destroy, :index]
 
  
  def index
    @artists = @billboard.artists
  end

  def show

  end

  def new
    @artist = @billboard.artists.new
    render partial: "form"
  end

  
  def create
    @artist = @billboard.artists.new(artist_params)
    
    if @artist.save
      redirect_to [@billboard, @artist]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@billboard, @artist]
    else
      render :edit
    end

  end

  def destroy
    @artist.destroy
    redirect_to billboard_artists_path
   
  end


 private
  def set_billboard
    @billboard = Billboard.find(params[:billboard_id])
  end

  def set_artist
   @artist = Artist.find_by_id(params[:id])
  end
  

  def artist_params
   params.require(:artist).permit(:name, :genre, :bio)
  end


end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :update, :edit, :destroy]
  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
    render partial: "form"
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :edit
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboards_path
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private
  def set_billboard
    @billboard = Billboard.find(params[:id])
  end

  def billboard_params
    params.require(:billboard).permit(:chart)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist

  
  def index
    @songs = Song.all  
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to billboard_artists_path(@artist.billboard_id, @artist)
    else
      render :new
    end
  end

  def edit
  end

  def destroy
  end 

  private  

  def set_artist
    @artist = Artist.find_by_id(params[:artist_id])
  end

  def song_params
   params.require(:song).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/billboard_helper.rb
module BillboardHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_for [@billboard, @artist] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :genre %>
  <%= f.text_area :genre, required: true %>
  <%= f.label :bio %>
  <%= f.text_area :bio %>

  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Artist#edit</h1>
<p>Find me in app/views/artist/edit.html.erb</p>

app/views/artists/index.html.erb
<hr/>
<h1 class="ui header">Click a Artist To View Their Songs</h1>
<h2><%= link_to 'Billboard: Top songs', artist_songs_path(@artists) %></h2>
<h4><%= link_to 'Create a new artist', new_billboard_artist_path(@billboard) %></h4>
<div class="ui divider"></div>
<div class="ui grid">
<ol>
  <% @artists.each do |artist| %>
    <div class= "sixteen wide mobile eight wide tablet four wide computer column">
    <div class="ui card">
       </div>
          <div class="content">
           <li><%= link_to artist.name, [@billboard, artist] %></li>
          </div>
    </div>
    
  <% end %>
</ol>
</div>

app/views/artists/new.html.erb
<h1>Artist#new</h1>
<p>Find me in app/views/artist/new.html.erb</p>

app/views/artists/show.html.erb
<hr />
<h1><%= @artist.name %></h1>
<p><%= @artist.genre %></p>
<p><%= @artist.bio %></p>

<h2>song</h2>
<% @artist.songs.each do |song| %>
  <%= render 'songs/song', { song: song } %>
<hr />

<% end %>
<div class="extra content">

<button class="ui green basic button"><%= link_to 'Billboard: Top songs', artist_songs_path(@artist) %></button>
<button class="ui basic red button"><%= link_to 'Edit Artist', edit_billboard_artist_path([@billboard, @artist]) %></button>
<button class="ui basic blue button"><%= link_to 'Delete Artist', [@billboard, @artist], method: :delete %></button>
<button class="ui basic yellow button"><%= link_to 'Back To Artists', billboard_artists_path(@billboard) %></button>
<button class="ui basic purple button"><%= link_to 'Add Song', new_artist_song_path(@artist) %></button>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit Billboard' : 'Create Billboard' %></h1>
<hr />
<%= form_for @billboard do |f| %>
  <%= f.label :name %>
  <%= f.text_field :chart,   required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Billboard#edit</h1>
<p>Find me in app/views/billboard/edit.html.erb</p>

app/views/billboards/index.html.erb
<hr />
<h1 class="ui header">Click a Billboard To View Artists</h1>
<%= link_to 'Create a new billboard', new_billboard_path %>
<ul>
  <% @billboards.each do |billboard| %>
    <li><%= link_to billboard.chart, billboard %></li>
  <% end %>
</ul>

app/views/billboards/new.html.erb
<h1>Billboard#new</h1>
<p>Find me in app/views/billboard/new.html.erb</p>

app/views/billboards/show.html.erb
<hr />
<h1 class="ui header"><%= @billboard.chart %></h1>
<p>What would you like to do?</p><br>
  <button class="ui green basic button"><%= link_to 'View Artist', billboard_artists_path(@billboard) %></button>

  <button class="ui red basic button"><%= link_to 'Edit Billboard', edit_billboard_path(@billboard) %></button>

  <button class="ui brown basic button"><%= link_to 'Delete Billboard', @billboard, method: :delete %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard100</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="ui container">
  <div>
  <%= image_tag("djjayjay/dj.png") %>
  </div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/songs/_song.html.erb
<hr />
<p>Song: <%= song.name %></p>

</hr>

app/views/songs/edit.html.erb
<h1>Song#edit</h1>
<p>Find me in app/views/song/edit.html.erb</p>

app/views/songs/index.html.erb
<h1> Top Songs </h1>

<ol>
<% @songs.each do |song| %>
<li><%= song.name %></li>

<% end %>
</ol>
  <button class="ui green basic button"><%= link_to "Back", :back %></button>

app/views/songs/new.html.erb
<h1>Add A Song</h1>
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name, required: true %>
 

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1>Song#show</h1>
<p>Find me in app/views/song/show.html.erb</p>